"""C #4 rework (v6.82.0) — NATIVE GigaBuddy knowledge pipeline.

The mentor drops raw text files (.txt/.md/.docx) into ``employees/<id>/knowledge/``
WITHOUT any manual tags/[[links]]/headings. The pipeline extracts text and builds
the wiki (chunks + tags + cross-topic links) with the LLM (Karpathy methodology),
falling back to deterministic structural chunking when the LLM is unavailable.
The built wiki is persisted to ``knowledge/.wiki_index/index.json`` and rebuilt
when the folder changes; a ``knowledgeBase`` status field drives the panel
indicator. Still NOT RAG, still folder-confined / fail-soft / bounded.
"""

import json

import pytest

from ouroboros import gigabuddy_knowledge as gk
from ouroboros.gigabuddy_state import build_gigabuddy_view, default_gigabuddy_state


@pytest.fixture(autouse=True)
def _isolate_employees_root(tmp_path, monkeypatch):
    monkeypatch.setenv(
        "OUROBOROS_GIGABUDDY_EMPLOYEES_ROOT", str(tmp_path / "employees")
    )
    gk.clear_cache()
    yield
    gk.clear_cache()


def _kdir(tmp_path, employee_id="alice-demo"):
    d = tmp_path / "employees" / employee_id / "knowledge"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _write(kdir, name, text):
    (kdir / name).write_text(text, encoding="utf-8")


# --- Part 0/1: native ingest of RAW files (no manual markup) ------------------


def test_raw_txt_ingested_without_any_markup(tmp_path):
    kdir = _kdir(tmp_path)
    # plain prose, no #tags, no [[links]], no headings
    _write(kdir, "vpn.txt", "Как подключить VPN: установите клиент и войдите.")
    idx = gk.build_index("alice-demo", use_llm=False)
    assert not idx.is_empty()
    assert any("vpn" in c.source.lower() for c in idx.chunks)


def test_docx_supported_or_honestly_skipped(tmp_path):
    """`.docx` is extracted when a library is present, otherwise honestly skipped
    (never fabricated). Either way the pipeline does not raise."""
    kdir = _kdir(tmp_path)
    # a .docx we cannot easily synthesize here; assert the extractor contract:
    # _extract_text returns "" for an unreadable/absent-lib docx, never raises.
    fake = kdir / "policy.docx"
    fake.write_bytes(b"not a real docx")
    text = gk._extract_text(fake)  # must be fail-soft, never raise
    # honest fail-soft: None (unreadable / lib missing / invalid docx) or "" —
    # never a fabricated body. build_index treats both as "no text" and skips.
    assert text is None or isinstance(text, str)


def test_docx_extension_recognized_in_walker(tmp_path):
    assert ".docx" in gk._DOCX_EXTS
    assert ".txt" in gk._TEXT_EXTS
    assert ".md" in gk._TEXT_EXTS


# --- Part 1: LLM build (mocked) + deterministic fallback ---------------------


class _StubMsg(dict):
    pass


def _stub_llm_chat(payload):
    """Return a deterministic JSON wiki so we can assert LLM-built tags/links."""
    def _chat(**kwargs):
        return ({"content": json.dumps(payload, ensure_ascii=False)}, {})
    return _chat


def test_llm_build_produces_tags_and_links(tmp_path, monkeypatch):
    kdir = _kdir(tmp_path)
    _write(kdir, "access.txt", "Заявка на доступ подаётся через портал.")
    payload = {
        "chunks": [
            {
                "heading": "Оформление доступов",
                "body": "Заявка на доступ подаётся через портал заявок.",
                "tags": ["доступы", "портал"],
                "links": ["VPN"],
            }
        ]
    }
    monkeypatch.setattr(
        "ouroboros.llm.LLMClient.chat", lambda self, **kw: _stub_llm_chat(payload)()
    )
    idx = gk.build_index("alice-demo", use_llm=True)
    assert not idx.is_empty()
    c = idx.chunks[0]
    assert c.heading == "Оформление доступов"
    assert "доступы" in c.tags
    # cross-topic link generated by the LLM (normalized topic key)
    assert any("vpn" in l for l in c.links)
    assert idx.llm_built is True


def test_llm_failure_falls_back_to_structural(tmp_path, monkeypatch):
    kdir = _kdir(tmp_path)
    _write(kdir, "vac.txt", "Отпуск оформляется через HR-систему за две недели.")

    def _boom(self, **kw):
        raise RuntimeError("provider down")

    monkeypatch.setattr("ouroboros.llm.LLMClient.chat", _boom)
    idx = gk.build_index("alice-demo", use_llm=True)
    # still built (deterministic fallback), just not llm_built
    assert not idx.is_empty()
    assert idx.llm_built is False


def test_hot_path_never_calls_llm(tmp_path, monkeypatch):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN: установите клиент.")
    called = {"n": 0}

    def _spy(self, **kw):
        called["n"] += 1
        return ({"content": "{}"}, {})

    monkeypatch.setattr("ouroboros.llm.LLMClient.chat", _spy)
    # get_index / knowledge_context_block are the hot path — no LLM allowed
    gk.get_index("alice-demo")
    gk.knowledge_context_block("alice-demo", "vpn")
    gk.knowledge_status("alice-demo")
    assert called["n"] == 0


# --- Part 2: persistence / status / rebuild / auto-update ---------------------


def test_status_lifecycle_empty_building_ready(tmp_path):
    # empty
    assert gk.knowledge_status("alice-demo")["status"] == "empty"
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN текст.")
    gk.clear_cache()
    # sources present, not built yet → building
    assert gk.knowledge_status("alice-demo")["status"] == "building"
    # build + persist → ready
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    st = gk.knowledge_status("alice-demo")
    assert st["status"] == "ready"
    assert st["docCount"] == 1
    assert st["chunkCount"] >= 1


def test_wiki_index_persisted_in_service_dir(tmp_path):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN текст.")
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    wi = kdir / ".wiki_index" / "index.json"
    assert wi.exists()
    data = json.loads(wi.read_text(encoding="utf-8"))
    assert data["schema"] == gk._WIKI_INDEX_SCHEMA
    assert isinstance(data["chunks"], list) and data["chunks"]


def test_service_dir_excluded_from_ingest(tmp_path):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN текст.")
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    sig_before = gk._live_signature("alice-demo")
    # rebuilding again must not change the source signature (index dir excluded)
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    assert gk._live_signature("alice-demo") == sig_before


def test_delete_source_marks_building_again(tmp_path):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN текст.")
    _write(kdir, "vac.txt", "Отпуск текст.")
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    assert gk.knowledge_status("alice-demo")["status"] == "ready"
    (kdir / "vpn.txt").unlink()
    gk.clear_cache()
    # folder composition changed → stale persisted index → building
    assert gk.knowledge_status("alice-demo")["status"] == "building"


def test_persisted_index_survives_reload(tmp_path):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "VPN: установите клиент и войдите.")
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    gk.clear_cache()
    # load straight from disk (no rebuild) and retrieve
    loaded = gk.load_persisted_index("alice-demo")
    assert loaded is not None and not loaded.is_empty()


# --- retrieval + honest empty -------------------------------------------------


def test_retrieval_relevant_and_honest_empty(tmp_path):
    kdir = _kdir(tmp_path)
    _write(kdir, "vpn.txt", "Как подключить VPN: установите клиент, войдите логином.")
    _write(kdir, "access.txt", "Как оформить доступы: заявка через портал заявок.")
    gk.rebuild_knowledge("alice-demo", use_llm=False)
    block = gk.knowledge_context_block("alice-demo", "как оформить доступы")
    assert "доступ" in block.lower()
    block2 = gk.knowledge_context_block("alice-demo", "рецепт борща")
    assert "не" in block2.lower()  # honest "not in the base" note


# --- Part 3: knowledgeBase view field ----------------------------------------


def test_view_exposes_knowledge_base_status_empty(tmp_path):
    state = default_gigabuddy_state()
    view = build_gigabuddy_view(state)
    kb = view.get("knowledgeBase")
    assert isinstance(kb, dict)
    assert set(kb.keys()) >= {"status", "docCount", "chunkCount"}
    # blank/neutral default employee → no knowledge folder → empty
    assert kb["status"] in {"empty", "building", "ready", "error"}


def test_view_knowledge_base_ready_counts(tmp_path):
    kdir = _kdir(tmp_path, "novice")
    _write(kdir, "vpn.txt", "VPN текст.")
    gk.rebuild_knowledge("novice", use_llm=False)
    state = default_gigabuddy_state()  # default active employee id == "novice"
    view = build_gigabuddy_view(state)
    kb = view["knowledgeBase"]
    assert kb["status"] == "ready"
    assert kb["docCount"] == 1
