"""Static UI contracts for page chrome: shared header helper, scroll regions,
and evolution/consciousness wiring.

Consolidated in v5.15.x from three small files that each guarded one slice
of the SPA page-chrome layer:

- ``test_page_header_ui_static.py``        — renderPageHeader / renderTabStrip SSOT
- ``test_settings_and_page_layout_static.py`` — secrets generality + scroll regions
- ``test_evolution_ui_guards.py``          — evolution page + server runtime-state wiring
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Shared page header helper (renderPageHeader / renderTabStrip SSOT)
# ---------------------------------------------------------------------------


def test_shared_page_header_helper_has_no_inline_styles():
    source = _read("web/modules/page_header.js")

    assert "export function renderPageHeader" in source
    assert "export function renderTabStrip" in source
    assert "style=" not in source
    assert "app-page-header" in source
    assert "app-tab-strip" in source


def test_primary_pages_use_shared_header_helper():
    for rel in [
        "web/modules/settings_ui.js",
        "web/modules/dashboard.js",
        "web/modules/skills.js",
        "web/modules/widgets.js",
        "web/modules/files.js",
        "web/modules/chat.js",
    ]:
        source = _read(rel)
        assert "page_header.js" in source
        assert "renderPageHeader" in source


# ---------------------------------------------------------------------------
# Settings secrets layout + skills/widgets scroll regions
# ---------------------------------------------------------------------------


def test_settings_secrets_are_generic_and_integrations_tab_removed():
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "Integrations" not in ui
    assert "TELEGRAM_" not in ui
    assert "TELEGRAM_" not in settings
    assert "skill-requested-secrets" in ui
    assert "custom-secrets-list" in ui
    assert "Source Control" in ui


def test_settings_scope_review_effort_round_trips():
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "s-effort-scope-review" in ui
    assert "OUROBOROS_EFFORT_SCOPE_REVIEW" in settings
    assert "['s-effort-scope-review', 'OUROBOROS_EFFORT_SCOPE_REVIEW', 'high']" in settings
    assert "key !== 'OUROBOROS_RUNTIME_MODE' && key !== 'OUROBOROS_CONTEXT_MODE'" in settings


def test_settings_mutative_subagents_toggle_round_trips():
    """The owner-facing master switch for mutative ("acting") subagents must exist
    as an explicit On/Off control wired through the
    settings load/save path, not only as a settings.json/env key."""
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "s-allow-mutative-subagents" in ui
    assert "Mutative Subagents" in ui
    section_start = ui.index("<h3>Mutative Subagents</h3>")
    section_end = ui.index('<div class="form-section">', section_start + 1)
    section = ui[section_start:section_end]
    # Segmented control is generated by the renderSegmentedField SSOT (C7.1): the
    # Off/On options live in its `options` array, not inline button markup.
    assert "renderSegmentedField" in section
    assert "target: 's-allow-mutative-subagents'" in section
    assert "value: 'auto'" not in section
    assert "value: 'off'" in section
    assert "value: 'on'" in section
    # load + save mapping wired in settings.js (outside VALUE_FIELDS)
    assert "OUROBOROS_ALLOW_MUTATIVE_SUBAGENTS" in settings
    assert "s-allow-mutative-subagents" in settings
    assert "dataset.rawValue = rawMutative" in settings
    assert "mutativeTouched" in settings


def test_onboarding_compact_access_step_keeps_default_width_two_column():
    css = _read("web/onboarding.css")
    assert "@media (max-height: 820px), (max-width: 900px)" in css
    assert ".field-note,\n  .footer-copy" in css
    assert "@media (max-width: 760px)" in css


def test_subagent_write_surface_badge_in_both_card_paths():
    """The write=<surface> badge must render on BOTH the Logs path
    (summarizeLogEvent) and the Chat live-card path (summarizeChatLiveEvent),
    not just one — the surface field is plumbed through history/contracts."""
    log_events = _read("web/modules/log_events.js")
    # both summarize functions reference the badge
    assert log_events.count("write=${evt.write_surface}") >= 2
    api_types = _read("web/modules/api_types.js")
    assert "write_surface" in api_types


def test_skills_and_widgets_use_inner_scroll_regions():
    skills = _read("web/modules/skills.js")
    widgets = _read("web/modules/widgets.js")
    css = _read("web/style.css")
    assert 'class="skills-scroll scroll-fade-y"' in skills
    assert 'class="widgets-scroll scroll-fade-y"' in widgets
    assert ".skills-scroll" in css and "overflow-y: auto" in css
    assert ".widgets-scroll" in css and "overflow-y: auto" in css


# ---------------------------------------------------------------------------
# Evolution / consciousness UI wiring
# ---------------------------------------------------------------------------


def test_evolution_page_supports_refresh_and_runtime_state():
    source = _read("web/modules/evolution.js")

    assert 'id="evo-refresh"' in source
    assert "Runtime Status" in source
    assert "apiFetch(`/api/evolution-data${suffix}`" in source
    assert "ws.on('open', () => {" in source
    assert "window.addEventListener('ouro:page-shown'" in source
    assert "document.addEventListener('visibilitychange'" in source
    assert "renderRuntimeState(runtime, data.generated_at || '');" in source
    assert "evolution_state" in source
    assert "bg_consciousness_state" in source


def test_gigabuddy_product_mode_is_reversible_ui_overlay():
    config = _read("ouroboros/config.py")
    app = _read("web/app.js")
    chat = _read("web/modules/chat.js")
    gigabuddy = _read("web/modules/gigabuddy.js")
    settings = _read("web/modules/settings.js")
    settings_ui = _read("web/modules/settings_ui.js")
    api_client = _read("web/modules/api_client.js")
    css = _read("web/style.css")
    state = _read("ouroboros/gateway/state.py")
    contracts = _read("ouroboros/gateway/contracts.py")

    assert '"OUROBOROS_PRODUCT_MODE": ""' in config
    assert '"OUROBOROS_PRODUCT_MODE"' in config and "apply_settings_to_env" in config
    assert "apiClient.settings()" in app
    assert "applyGigaBuddyMode(settings)" in app
    assert "body.dataset.productMode" in gigabuddy
    assert "renderGigaBuddyTrackPanel" in chat
    assert "refreshGigaBuddyPanel" in chat and "bindGigaBuddyPanel" in chat
    assert "gigaBuddy: (op, payload = {})" in api_client
    assert "ouro:gigabuddy-mode-changed" in app
    assert "data-gigabuddy-action" not in gigabuddy
    assert "data-gigabuddy-add-task" not in gigabuddy
    assert "gigabuddy-admin-actions" not in gigabuddy
    assert "Подтвердить переход" not in gigabuddy
    assert "Быстрый виток" not in gigabuddy
    assert "Откат к заботе" not in gigabuddy
    assert "Задача от наставника" not in gigabuddy
    assert "Наставнический контур" in gigabuddy
    assert "Советчик" in gigabuddy and "Помощник" in gigabuddy and "Партнёр" in gigabuddy
    # Decluttered novice panel (v6.75.1): no micro-checklist tasks, no v1/rollback
    # system line, no mentor-only readiness block, no questionnaire/domain package.
    assert "gigabuddy-track-task" not in gigabuddy
    assert "Готовность к переходу" not in gigabuddy
    assert "Прогресс сохраняется при откате" not in gigabuddy
    assert "Базовый опросник" not in gigabuddy
    assert "gigabuddy-questionnaire" not in gigabuddy
    # The questionnaire block is replaced by a link to the knowledge-source folder.
    assert "Материалы базы знаний" in gigabuddy
    assert "gigabuddy/employees/" in gigabuddy and "/knowledge/" in gigabuddy
    assert "s-product-mode" in settings and "OUROBOROS_PRODUCT_MODE" in settings
    assert "Product Mode" in settings_ui and "ГигаБадди" in settings_ui
    assert "GIGABUDDY_ADMIN_PIN" in settings_ui
    assert "data-gigabuddy-return-form" in gigabuddy
    assert "gigaBuddyReturn" in chat
    assert "gigaBuddyReturn" in api_client and "gigabuddy_return" in api_client
    assert "GIGABUDDY_ADMIN_PIN" in _read("ouroboros/gateway/settings.py")
    assert "_generic_gigabuddy_settings_guard" in _read("ouroboros/gateway/settings.py")
    assert "body.product-gigabuddy #page-chat .chat-composer-pills" in css
    assert "body.product-gigabuddy #primary-sidebar .nav-utilities" in css
    assert 'body.product-gigabuddy #page-chat [data-chat-command="restart"]' in css
    assert "body.product-gigabuddy #page-chat .chat-header-more" in css
    # Emergency Stop remains visible/structurally available; product mode hides other novice chrome only.
    assert "body.product-gigabuddy #page-chat .chat-header-actions {\n    display: flex;" in css
    assert "data-chat-command=\"panic\"" in chat
    assert "cmd: '/panic'" in chat
    assert "not a security boundary" in settings_ui
    # P0 deliberately uses /api/settings, not a new frozen /api/state field.
    assert "product_mode" not in state
    assert "product_mode" not in contracts



def test_gigabuddy_interface_personalization_surface():
    """The panel reads live profile/track state and applies interface attributes
    to the shell through the settings seam (no frozen route / contracts edit)."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    css = _read("web/style.css")
    contracts = _read("ouroboros/gateway/contracts.py")

    # Interface personalization is applied to the shell (theme/tone/accent) via
    # body data attributes + a CSS custom property — validated, no inline styles.
    assert "applyGigaBuddyInterface" in gigabuddy
    assert "body.dataset.gigabuddyTheme" in gigabuddy
    assert "body.dataset.gigabuddyTone" in gigabuddy
    assert "setProperty('--gigabuddy-accent'" in gigabuddy
    # Only CSS-custom-property mutation is allowed; no static inline style props.
    for banned in ["style.color", "style.display", "style.background", "style.width"]:
        assert banned not in gigabuddy
    # The panel renders live profile + adaptation track (not static copy only).
    assert "state.profile" in gigabuddy and "state.track" in gigabuddy
    assert "gigabuddy-adapt-track" in gigabuddy and "gigabuddy-chip" in gigabuddy
    assert "Профиль новичка" in gigabuddy
    # Interface is applied on refresh and reset when leaving product mode.
    assert "applyGigaBuddyInterface(normalizeView(view).interface" in gigabuddy
    assert "resetGigaBuddyInterface" in gigabuddy
    # Accent stays inside the design system via a CSS variable with crimson fallback.
    assert "--gigabuddy-accent" in css
    assert "gigabuddy-adapt-track" in css and "gigabuddy-chip" in css
    # Still no frozen /api/state contract churn for the personalization data.
    assert "gigabuddy" not in contracts.lower()


def test_gigabuddy_three_column_layout_and_novice_thread(tmp_path=None):
    """B1 (v6.76.0): cohesive 3-column product-mode layout (track / novice chat /
    panel) with a backend-partitioned novice thread reusing project chat_id
    routing. No project-room overlay; no frozen contract churn."""
    chat = _read("web/modules/chat.js")
    gigabuddy = _read("web/modules/gigabuddy.js")
    app = _read("web/app.js")
    css = _read("web/style.css")
    state = _read("ouroboros/gateway/state.py")
    settings = _read("ouroboros/gateway/settings.py")
    gb_state = _read("ouroboros/gigabuddy_state.py")
    contracts = _read("ouroboros/gateway/contracts.py")

    # --- chat.js: the 3 slots exist, and only in the main (!asPanel) branch so a
    # novice asPanel instance never recursively renders the product layout.
    assert "gigabuddy-product-layout" in chat
    assert "data-gigabuddy-track-slot" in chat
    assert "data-gigabuddy-novice-chat-slot" in chat
    assert "data-gigabuddy-panel-slot" in chat
    assert "gigabuddy-novice-placeholder" in chat
    layout_idx = chat.index("gigabuddy-product-layout")
    # The layout markup sits inside a `${!asPanel ? ... : ''}` guard.
    assert "!asPanel ?" in chat[max(0, layout_idx - 400):layout_idx]

    # --- gigabuddy.js: single get_state owner publishes the novice descriptor.
    assert "ouro:gigabuddy-novice-chat" in gigabuddy
    assert "noviceChat" in gigabuddy

    # --- app.js: mounts the isolated center chat, with same-tick routing guard,
    # invalid-descriptor placeholder fallback, event-supplied projectId, and a
    # placeholder-clearing replaceChildren before mounting.
    assert "ouro:gigabuddy-novice-chat" in app
    assert "data-gigabuddy-novice-chat-slot" in app
    assert "state.projectChatIds.add" in app
    assert "replaceChildren()" in app
    assert "idPrefix: 'gigabuddy-novice'" in app
    assert "createChatInstance(" in app
    # invalid descriptor keeps an explicit placeholder rather than mounting.
    assert "gigabuddy-novice-placeholder" in app

    # --- CSS: grid layout on the wrapper, scoped panel visibility (base panel
    # keeps display:none), narrow direct-child hide of the developer transcript,
    # a center-slot flex contract, and NO positioning left on the panel itself.
    assert "body.product-gigabuddy #page-chat .gigabuddy-product-layout {" in css
    assert "display: grid;" in css
    assert "body.product-gigabuddy #page-chat .gigabuddy-panel-slot > .gigabuddy-track-panel {" in css
    assert "body.product-gigabuddy #page-chat > #chat-messages" in css
    assert ".gigabuddy-novice-chat-slot {" in css
    # The panel's own rule must no longer carry positioning props (they moved to
    # the slot); guard the exact base-rule block.
    panel_rule_start = css.index(".gigabuddy-track-panel {")
    panel_rule_end = css.index("}", panel_rule_start)
    panel_rule = css[panel_rule_start:panel_rule_end]
    for banned in ["position: absolute", "top:", "right:", "bottom:", "width:", "min-width:", "max-height:"]:
        assert banned not in panel_rule
    # But it keeps its visual card styling.
    assert "border-radius:" in panel_rule and "backdrop-filter:" in panel_rule

    # --- backend: novice-project registry bridge + eager /api/state registration
    # + gateway view injection; the reducer/view stay pure and no contract churn.
    assert "def ensure_novice_project" in gb_state
    assert 'NOVICE_PROJECT_ID = "gigabuddy-novice"' in gb_state
    assert "ensure_novice_project" in state
    assert 'OUROBOROS_PRODUCT_MODE", "").strip().lower() == "gigabuddy"' in state
    assert "ensure_novice_project" in settings
    assert '"noviceChat"' in settings and '"chatId"' in settings
    assert "gigabuddy" not in contracts.lower()

    # Panic + PIN-return preserved.
    assert 'data-chat-command="panic"' in chat
    assert "data-gigabuddy-return-form" in gigabuddy


def test_server_navigation_and_chat_static_contracts():
    server_source = _read("server.py")
    state_source = _read("ouroboros/gateway/state.py")
    control_source = _read("ouroboros/gateway/control.py")
    app_source = _read("web/app.js")
    evo_source = _read("web/modules/evolution.js")
    chat_source = _read("web/modules/chat.js")
    css = _read("web/style.css")
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    costs = _read("web/modules/costs.js")

    assert "def _describe_bg_consciousness_state(requested_enabled: bool) -> dict:" in server_source
    assert '"evolution_state": evolution_state,' in state_source
    assert '"bg_consciousness_state": bg_state,' in state_source
    assert 'request.query_params.get("force")' in control_source
    assert "window.dispatchEvent(new CustomEvent('ouro:page-shown', { detail: { page: pageName } }));" in app_source
    assert "evo-runtime-detail" in evo_source
    assert "data?.evolution_state?.detail" in chat_source
    assert "data?.bg_consciousness_state?.detail" in chat_source
    assert re.search(r'<input[^>]+id="chat-file-input"[^>]+multiple', chat_source)
    assert "MAX_PENDING_ATTACHMENTS = 10" in chat_source
    assert "MAX_ATTACHMENT_FILE_BYTES = 50 * 1024 * 1024" in chat_source
    assert "MAX_PENDING_ATTACHMENT_BYTES = 100 * 1024 * 1024" in chat_source
    assert "pendingAttachments" in chat_source
    assert "attachmentsUploading" in chat_source
    assert "setAttachmentUploadState" in chat_source
    assert "attachBtn.classList.toggle('uploading', uploading)" in chat_source
    assert "input.disabled = uploading;" in chat_source
    assert "cleanupUploadedAttachments" in chat_source
    assert "method: 'DELETE'" in chat_source
    assert "await cleanupUploadedAttachments(uploaded);" in chat_source
    assert "await cleanupUploadedAttachments(uploadedAttachments);" in chat_source
    assert "ws.send({" in chat_source and "{ queue: false }" in chat_source
    assert "result?.status !== 'sent'" in chat_source
    assert "data-attachment-remove" in chat_source
    assert "Promise.allSettled" in chat_source
    assert '>Loading…</span>' in chat_source
    assert "syncHeaderControlState({ accounting: { available: false } });" in chat_source
    assert "budget_text: 'Connecting...'" not in chat_source
    assert "send(msg, options = {})" in _read("web/modules/ws.js")
    assert "options.queue === false" in _read("web/modules/ws.js")
    assert ".chat-attachment-preview" in css and "flex-wrap" in css
    assert 'id="s-total-budget"' in ui
    assert 'id="s-settings-per-task-cost"' in ui
    assert "setupContract.budgetFields" in settings
    assert "'anthropic/claude-opus-4.7'" in settings
    assert "'anthropic::claude-opus-4-7'" in settings
    assert "currentSettings?.[field.settingKey]" in settings
    assert "window.addEventListener('ouro:settings-updated'" in settings
    assert "source: 'settings'" in settings
    assert "Budget values must be at least 0.01." in costs
    assert "COST_BUDGET_INPUTS" in costs
    assert "s?._meta?.setup_contract?.budgetFields" in costs
    assert "const MIN_BUDGET_VALUE" not in costs
    assert "new CustomEvent('ouro:settings-updated'" in costs
    assert "source: 'costs'" in costs
    assert "event.detail?.source === 'costs'" in costs
