"""Static UI contracts for page chrome: shared header helper, scroll regions,
and evolution/consciousness wiring.

Consolidated in v5.15.x from three small files that each guarded one slice
of the SPA page-chrome layer:

- ``test_page_header_ui_static.py``        — renderPageHeader / renderTabStrip SSOT
- ``test_settings_and_page_layout_static.py`` — secrets generality + scroll regions
- ``test_evolution_ui_guards.py``          — evolution page + server runtime-state wiring
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Shared page header helper (renderPageHeader / renderTabStrip SSOT)
# ---------------------------------------------------------------------------


def test_shared_page_header_helper_has_no_inline_styles():
    source = _read("web/modules/page_header.js")

    assert "export function renderPageHeader" in source
    assert "export function renderTabStrip" in source
    assert "style=" not in source
    assert "app-page-header" in source
    assert "app-tab-strip" in source


def test_primary_pages_use_shared_header_helper():
    for rel in [
        "web/modules/settings_ui.js",
        "web/modules/dashboard.js",
        "web/modules/skills.js",
        "web/modules/widgets.js",
        "web/modules/files.js",
        "web/modules/chat.js",
    ]:
        source = _read(rel)
        assert "page_header.js" in source
        assert "renderPageHeader" in source


# ---------------------------------------------------------------------------
# Settings secrets layout + skills/widgets scroll regions
# ---------------------------------------------------------------------------


def test_settings_secrets_are_generic_and_integrations_tab_removed():
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "Integrations" not in ui
    assert "TELEGRAM_" not in ui
    assert "TELEGRAM_" not in settings
    assert "skill-requested-secrets" in ui
    assert "custom-secrets-list" in ui
    assert "Source Control" in ui


def test_settings_scope_review_effort_round_trips():
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "s-effort-scope-review" in ui
    assert "OUROBOROS_EFFORT_SCOPE_REVIEW" in settings
    assert "['s-effort-scope-review', 'OUROBOROS_EFFORT_SCOPE_REVIEW', 'high']" in settings
    assert "key !== 'OUROBOROS_RUNTIME_MODE' && key !== 'OUROBOROS_CONTEXT_MODE'" in settings


def test_settings_mutative_subagents_toggle_round_trips():
    """The owner-facing master switch for mutative ("acting") subagents must exist
    as an explicit On/Off control wired through the
    settings load/save path, not only as a settings.json/env key."""
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    assert "s-allow-mutative-subagents" in ui
    assert "Mutative Subagents" in ui
    section_start = ui.index("<h3>Mutative Subagents</h3>")
    section_end = ui.index('<div class="form-section">', section_start + 1)
    section = ui[section_start:section_end]
    # Segmented control is generated by the renderSegmentedField SSOT (C7.1): the
    # Off/On options live in its `options` array, not inline button markup.
    assert "renderSegmentedField" in section
    assert "target: 's-allow-mutative-subagents'" in section
    assert "value: 'auto'" not in section
    assert "value: 'off'" in section
    assert "value: 'on'" in section
    # load + save mapping wired in settings.js (outside VALUE_FIELDS)
    assert "OUROBOROS_ALLOW_MUTATIVE_SUBAGENTS" in settings
    assert "s-allow-mutative-subagents" in settings
    assert "dataset.rawValue = rawMutative" in settings
    assert "mutativeTouched" in settings


def test_onboarding_compact_access_step_keeps_default_width_two_column():
    css = _read("web/onboarding.css")
    assert "@media (max-height: 820px), (max-width: 900px)" in css
    assert ".field-note,\n  .footer-copy" in css
    assert "@media (max-width: 760px)" in css


def test_subagent_write_surface_badge_in_both_card_paths():
    """The write=<surface> badge must render on BOTH the Logs path
    (summarizeLogEvent) and the Chat live-card path (summarizeChatLiveEvent),
    not just one — the surface field is plumbed through history/contracts."""
    log_events = _read("web/modules/log_events.js")
    # both summarize functions reference the badge
    assert log_events.count("write=${evt.write_surface}") >= 2
    api_types = _read("web/modules/api_types.js")
    assert "write_surface" in api_types


def test_skills_and_widgets_use_inner_scroll_regions():
    skills = _read("web/modules/skills.js")
    widgets = _read("web/modules/widgets.js")
    css = _read("web/style.css")
    assert 'class="skills-scroll scroll-fade-y"' in skills
    assert 'class="widgets-scroll scroll-fade-y"' in widgets
    assert ".skills-scroll" in css and "overflow-y: auto" in css
    assert ".widgets-scroll" in css and "overflow-y: auto" in css


# ---------------------------------------------------------------------------
# Evolution / consciousness UI wiring
# ---------------------------------------------------------------------------


def test_evolution_page_supports_refresh_and_runtime_state():
    source = _read("web/modules/evolution.js")

    assert 'id="evo-refresh"' in source
    assert "Runtime Status" in source
    assert "apiFetch(`/api/evolution-data${suffix}`" in source
    assert "ws.on('open', () => {" in source
    assert "window.addEventListener('ouro:page-shown'" in source
    assert "document.addEventListener('visibilitychange'" in source
    assert "renderRuntimeState(runtime, data.generated_at || '');" in source
    assert "evolution_state" in source
    assert "bg_consciousness_state" in source


def test_gigabuddy_product_mode_is_reversible_ui_overlay():
    config = _read("ouroboros/config.py")
    app = _read("web/app.js")
    chat = _read("web/modules/chat.js")
    gigabuddy = _read("web/modules/gigabuddy.js")
    settings = _read("web/modules/settings.js")
    settings_ui = _read("web/modules/settings_ui.js")
    api_client = _read("web/modules/api_client.js")
    css = _read("web/style.css")
    state = _read("ouroboros/gateway/state.py")
    contracts = _read("ouroboros/gateway/contracts.py")

    assert '"OUROBOROS_PRODUCT_MODE": ""' in config
    assert '"OUROBOROS_PRODUCT_MODE"' in config and "apply_settings_to_env" in config
    assert "apiClient.settings()" in app
    assert "applyGigaBuddyMode(settings)" in app
    assert "body.dataset.productMode" in gigabuddy
    assert "renderGigaBuddyTrackPanel" in chat
    assert "refreshGigaBuddyPanel" in chat and "bindGigaBuddyPanel" in chat
    assert "gigaBuddy: (op, payload = {})" in api_client
    assert "ouro:gigabuddy-mode-changed" in app
    assert "data-gigabuddy-action" not in gigabuddy
    assert "data-gigabuddy-add-task" not in gigabuddy
    assert "gigabuddy-admin-actions" not in gigabuddy
    assert "Подтвердить переход" not in gigabuddy
    assert "Быстрый виток" not in gigabuddy
    assert "Откат к заботе" not in gigabuddy
    assert "Задача от наставника" not in gigabuddy
    assert "Наставнический контур" in gigabuddy
    assert "Советчик" in gigabuddy and "Помощник" in gigabuddy and "Партнёр" in gigabuddy
    # Decluttered novice panel (v6.75.1): no micro-checklist tasks, no v1/rollback
    # system line, no mentor-only readiness block, no questionnaire/domain package.
    assert "gigabuddy-track-task" not in gigabuddy
    assert "Готовность к переходу" not in gigabuddy
    assert "Прогресс сохраняется при откате" not in gigabuddy
    assert "Базовый опросник" not in gigabuddy
    assert "gigabuddy-questionnaire" not in gigabuddy
    # The questionnaire block is replaced by a link to the knowledge-source folder.
    assert "Материалы базы знаний" in gigabuddy
    assert "gigabuddy/employees/" in gigabuddy and "/knowledge/" in gigabuddy
    assert "s-product-mode" in settings and "OUROBOROS_PRODUCT_MODE" in settings
    assert "Product Mode" in settings_ui and "ГигаБадди" in settings_ui
    assert "GIGABUDDY_ADMIN_PIN" in settings_ui
    assert "data-gigabuddy-return-form" in gigabuddy
    assert "gigaBuddyReturn" in chat
    assert "gigaBuddyReturn" in api_client and "gigabuddy_return" in api_client
    assert "GIGABUDDY_ADMIN_PIN" in _read("ouroboros/gateway/settings.py")
    assert "_generic_gigabuddy_settings_guard" in _read("ouroboros/gateway/settings.py")
    assert "body.product-gigabuddy #page-chat .chat-composer-pills" in css
    assert "body.product-gigabuddy #primary-sidebar .nav-utilities" in css
    assert 'body.product-gigabuddy #page-chat [data-chat-command="restart"]' in css
    assert "body.product-gigabuddy #page-chat .chat-header-more" in css
    # Emergency Stop remains visible/structurally available; product mode hides other novice chrome only.
    assert "body.product-gigabuddy #page-chat .chat-header-actions {\n    display: flex;" in css
    assert "data-chat-command=\"panic\"" in chat
    assert "cmd: '/panic'" in chat
    assert "not a security boundary" in settings_ui
    # P0 deliberately uses /api/settings, not a new frozen /api/state field.
    assert "product_mode" not in state
    assert "product_mode" not in contracts



def test_gigabuddy_interface_personalization_surface():
    """The panel reads live profile/track state and applies interface attributes
    to the shell through the settings seam (no frozen route / contracts edit)."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    css = _read("web/style.css")
    contracts = _read("ouroboros/gateway/contracts.py")

    # Interface personalization is applied to the shell (theme/tone/accent) via
    # body data attributes + a CSS custom property — validated, no inline styles.
    assert "applyGigaBuddyInterface" in gigabuddy
    assert "body.dataset.gigabuddyTheme" in gigabuddy
    assert "body.dataset.gigabuddyTone" in gigabuddy
    assert "setProperty('--gigabuddy-accent'" in gigabuddy
    # Only CSS-custom-property mutation is allowed; no static inline style props.
    for banned in ["style.color", "style.display", "style.background", "style.width"]:
        assert banned not in gigabuddy
    # The panel renders live profile + adaptation track (not static copy only).
    assert "state.profile" in gigabuddy and "state.track" in gigabuddy
    assert "gigabuddy-adapt-track" in gigabuddy and "gigabuddy-chip" in gigabuddy
    assert "Профиль новичка" in gigabuddy
    # Interface is applied on refresh and reset when leaving product mode.
    assert "applyGigaBuddyInterface(normalizeView(view).interface" in gigabuddy
    assert "resetGigaBuddyInterface" in gigabuddy
    # Accent stays inside the design system via a CSS variable with crimson fallback.
    assert "--gigabuddy-accent" in css
    assert "gigabuddy-adapt-track" in css and "gigabuddy-chip" in css
    # Still no frozen /api/state contract churn for the personalization data.
    assert "gigabuddy" not in contracts.lower()


def test_gigabuddy_fluffy_cat_theme_scoped_to_employee():
    """v6.87.7: the 'fluffy-cat' ui-depth evolution (light shell + animated
    8-bit cat) is strictly scoped to the employee whose own interface.theme
    carries the value — other employees and the plain shell are untouched."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    css = _read("web/style.css")
    state_py = _read("ouroboros/gigabuddy_state.py")

    # The theme is a validated enum member on BOTH sides (js shell + reducer).
    assert "'fluffy-cat'" in gigabuddy
    assert '"fluffy-cat"' in state_py
    # All light-shell rules are gated on the per-employee body attribute, never
    # on the global product-mode class — so they cannot leak to other employees.
    assert 'body[data-gigabuddy-theme="fluffy-cat"]' in css
    assert "body.product-gigabuddy .message" not in css or 'fluffy-cat' in css
    # Pixel cat: CSS-only sprite (box-shadow art, no external assets) + hop
    # keyframes, mounted/unmounted from JS only for this theme.
    assert "gigabuddy-pixel-cat" in css
    assert "@keyframes gigabuddy-cat-hop" in css
    assert "box-shadow:" in css
    assert "url(" not in css.split(".gigabuddy-pixel-cat")[1].split("@keyframes")[0]
    assert "syncGigaBuddyPixelCat" in gigabuddy
    # The cat mounts ONLY for fluffy-cat and is removed on any other theme/reset.
    assert "theme === 'fluffy-cat'" in gigabuddy
    assert "existing.remove()" in gigabuddy
    assert "syncGigaBuddyPixelCat(theme)" in gigabuddy
    assert "syncGigaBuddyPixelCat('neutral')" in gigabuddy


def test_gigabuddy_three_column_layout_and_novice_thread(tmp_path=None):
    """B1 (v6.76.0): cohesive 3-column product-mode layout (track / novice chat /
    panel) with a backend-partitioned novice thread reusing project chat_id
    routing. No project-room overlay; no frozen contract churn."""
    chat = _read("web/modules/chat.js")
    gigabuddy = _read("web/modules/gigabuddy.js")
    app = _read("web/app.js")
    css = _read("web/style.css")
    state = _read("ouroboros/gateway/state.py")
    settings = _read("ouroboros/gateway/settings.py")
    gb_state = _read("ouroboros/gigabuddy_state.py")
    contracts = _read("ouroboros/gateway/contracts.py")

    # --- chat.js: the 3 slots exist, and only in the main (!asPanel) branch so a
    # novice asPanel instance never recursively renders the product layout.
    assert "gigabuddy-product-layout" in chat
    assert "data-gigabuddy-track-slot" in chat
    assert "data-gigabuddy-novice-chat-slot" in chat
    assert "data-gigabuddy-panel-slot" in chat
    assert "gigabuddy-novice-placeholder" in chat
    layout_idx = chat.index("gigabuddy-product-layout")
    # The layout markup sits inside a `${!asPanel ? ... : ''}` guard.
    assert "!asPanel ?" in chat[max(0, layout_idx - 400):layout_idx]

    # --- gigabuddy.js: single get_state owner publishes the novice descriptor.
    assert "ouro:gigabuddy-novice-chat" in gigabuddy
    assert "noviceChat" in gigabuddy

    # --- app.js: mounts the isolated center chat, with same-tick routing guard,
    # invalid-descriptor placeholder fallback, event-supplied projectId, and a
    # placeholder-clearing replaceChildren before mounting.
    assert "ouro:gigabuddy-novice-chat" in app
    assert "data-gigabuddy-novice-chat-slot" in app
    assert "state.projectChatIds.add" in app
    assert "replaceChildren()" in app
    assert "idPrefix: 'gigabuddy-novice'" in app
    assert "createChatInstance(" in app
    # invalid descriptor keeps an explicit placeholder rather than mounting.
    assert "gigabuddy-novice-placeholder" in app

    # --- CSS: grid layout on the wrapper, scoped panel visibility (base panel
    # keeps display:none), narrow direct-child hide of the developer transcript,
    # a center-slot flex contract, and NO positioning left on the panel itself.
    assert "body.product-gigabuddy #page-chat .gigabuddy-product-layout {" in css
    assert "display: grid;" in css
    assert "body.product-gigabuddy #page-chat .gigabuddy-panel-slot > .gigabuddy-track-panel {" in css
    assert "body.product-gigabuddy #page-chat > #chat-messages" in css
    assert ".gigabuddy-novice-chat-slot {" in css
    # The panel's own rule must no longer carry positioning props (they moved to
    # the slot); guard the exact base-rule block.
    panel_rule_start = css.index(".gigabuddy-track-panel {")
    panel_rule_end = css.index("}", panel_rule_start)
    panel_rule = css[panel_rule_start:panel_rule_end]
    for banned in ["position: absolute", "top:", "right:", "bottom:", "width:", "min-width:", "max-height:"]:
        assert banned not in panel_rule
    # But it keeps its visual card styling.
    assert "border-radius:" in panel_rule and "backdrop-filter:" in panel_rule

    # --- backend: novice-project registry bridge + eager /api/state registration
    # + gateway view injection; the reducer/view stay pure and no contract churn.
    assert "def ensure_novice_project" in gb_state
    assert 'NOVICE_PROJECT_ID = "gigabuddy-novice"' in gb_state
    assert "ensure_novice_project" in state
    assert 'OUROBOROS_PRODUCT_MODE", "").strip().lower() == "gigabuddy"' in state
    assert "ensure_novice_project" in settings
    assert '"noviceChat"' in settings and '"chatId"' in settings
    assert "gigabuddy" not in contracts.lower()

    # Panic + PIN-return preserved.
    assert 'data-chat-command="panic"' in chat
    assert "data-gigabuddy-return-form" in gigabuddy


def test_gigabuddy_left_adaptation_track_is_live_and_expandable():
    """B2 (v6.78.0): the LEFT slot renders the employee's live adaptation track
    (stages/steps from view.track, NOT the advisor->partner role status), each
    stage an expandable <details>, with a neutral placeholder on an empty track,
    fed from the single get_state fetch owner, accent via the CSS variable."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    css = _read("web/style.css")

    # --- gigabuddy.js: the live left-track renderer exists and reads view.track.
    assert "renderGigaBuddyLeftTrack" in gigabuddy
    left_start = gigabuddy.index("function renderGigaBuddyLeftTrack")
    left_end = gigabuddy.index("\n}", left_start)
    left = gigabuddy[left_start:left_end]
    # Reads the live track (not static) and derives progress from it.
    assert "state.track" in left
    # Expandable stages the newcomer can "dive into".
    assert "<details" in left and "<summary>" in left
    # Neutral placeholder on an empty track — stages are never fabricated here.
    assert "gigabuddy-track-empty" in left
    # Per-stage steps rendered when present; a neutral hint when empty (B3/C fills).
    assert "item.steps" in left
    assert "gigabuddy-track-steps" in left
    # Content is escaped (no raw interpolation of employee-supplied strings).
    assert "escapeHtml(" in left

    # --- wired into the single get_state fetch owner, into the left slot only.
    refresh_start = gigabuddy.index("function refreshGigaBuddyPanel")
    refresh = gigabuddy[refresh_start:refresh_start + 900]
    assert "data-gigabuddy-track-slot" in refresh
    assert "renderGigaBuddyLeftTrack(view)" in refresh

    # --- CSS: the animated left track styling exists and follows the accent var;
    # no NEW inline styles are introduced in the renderer (CSS-only).
    assert ".gigabuddy-track-stage {" in css
    assert ".gigabuddy-track-stages {" in css or ".gigabuddy-track-stage[" in css
    assert "--gigabuddy-accent" in css
    assert ".style." not in left  # renderer emits classes/markup, not inline styles


def test_gigabuddy_novice_clean_command_is_visual_only():
    """v6.80.1: `/clean` is intercepted INSIDE the novice thread (this instance's
    projectId is the novice project) as a VISUAL-only transcript wipe. It never
    reaches the supervisor (not a runtime slash), never touches durable
    gigabuddy_state, and returns a FIXED neutral greeting as an EPHEMERAL bubble."""
    chat = _read("web/modules/chat.js")

    # Fixed, impersonal greeting constant + novice project id, both declared.
    assert "GIGABUDDY_NOVICE_PROJECT_ID = 'gigabuddy-novice'" in chat
    assert "const GIGABUDDY_CLEAN_GREETING = " in chat
    # The interception is gated to the novice thread and fires before any send.
    assert "isNoviceThread() && text === '/clean'" in chat
    assert "clearNoviceTranscript();" in chat
    # The clear helper wipes ONLY visible/session state, keeps the typing bubble,
    # and shows the fixed greeting as an ephemeral (never-persisted) bubble.
    clear_start = chat.index("function clearNoviceTranscript")
    clear_end = chat.index("\n    }", clear_start)
    clear = chat[clear_start:clear_end]
    assert "persistedHistory.length = 0" in clear
    assert "seenMessageKeys.clear()" in clear
    assert "sessionStorage.removeItem(storeKey(CHAT_STORAGE_KEY))" in clear
    assert "typing-bubble" in clear  # keeps the typing indicator
    assert "GIGABUDDY_CLEAN_GREETING" in clear
    assert "ephemeral: true" in clear  # greeting is not persisted to chat.jsonl
    # It must NOT call any reducer op / touch durable adaptation state.
    for durable in ["set_track", "record_progress", "load_profile", "apply_gigabuddy_action", "_action"]:
        assert durable not in clear
    # The greeting stays impersonal — no name/stage interpolation.
    greeting_line = next(l for l in chat.splitlines() if "GIGABUDDY_CLEAN_GREETING = " in l)
    assert "${" not in greeting_line  # a fixed string, not a template


def test_gigabuddy_b3_neutral_start_and_profile_parsing(tmp_path=None):
    """B3 (v6.79.0): a fresh install is the NEUTRAL, nameless novice — the
    synthetic Alice default is gone from both the backend reducer default and the
    frontend fallback; Alice/Leonid are loadable demo configs; profiles parse from
    the employee folder."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    gb_state = _read("ouroboros/gigabuddy_state.py")
    profile_mod = _read("ouroboros/gigabuddy_profile.py")

    # Backend default is the blank/neutral novice, NOT synthetic Alice.
    assert "BLANK_EMPLOYEE_ID" in gb_state
    assert "_blank_employee" in gb_state
    assert '"active_employee_id": BLANK_EMPLOYEE_ID' in gb_state
    # Alice/Leonid survive as LOADABLE demo profiles, not the hardcoded default.
    assert "_DEMO_PROFILES" in gb_state and "list_demo_profiles" in gb_state
    # The three B3 durable ops exist and are whitelisted.
    for op in ("load_profile", "set_track", "record_progress"):
        assert f'"{op}"' in gb_state

    # Frontend fallback is neutral: no synthetic Alice name/department, empty track.
    assert "activeEmployeeId: 'novice'" in gigabuddy
    assert "Алиса" not in gigabuddy
    assert "Люди и культура" not in gigabuddy
    assert "Базовый опросник" not in gigabuddy
    # Nameless-safe panel placeholders (never a fabricated person).
    assert "Профиль ещё не загружен" in gigabuddy

    # Profile parsing module: folder-confined, fail-soft, integration points for
    # the #4 knowledge (wiki) and #5 questionnaire skills.
    assert "employees_root" in profile_mod and "_is_confined" in profile_mod
    assert "def load_employee_profile" in profile_mod
    assert "def has_questionnaire" in profile_mod  # #5 integration point
    assert "def knowledge_dir_exists" in profile_mod  # #4 integration point


def test_gigabuddy_knowledge_base_status_indicator():
    """C#4 native pipeline (v6.82.0): the right panel shows a live knowledge-base
    build status indicator next to the knowledge-folder link — building/ready/
    empty/error + doc/chunk counts — fed from the get_state view (knowledgeBase),
    reducer view-pure, no frozen contract churn, CSS-only (no new inline styles)."""
    gigabuddy = _read("web/modules/gigabuddy.js")
    css = _read("web/style.css")
    gb_state = _read("ouroboros/gigabuddy_state.py")
    gk = _read("ouroboros/gigabuddy_knowledge.py")
    settings = _read("ouroboros/gateway/settings.py")
    contracts = _read("ouroboros/gateway/contracts.py")

    # --- gigabuddy.js: the indicator renderer exists, is normalized, and is wired
    # into the knowledge-link block of the track panel.
    assert "renderKnowledgeStatus" in gigabuddy
    assert "normalizeKnowledgeBase" in gigabuddy
    assert "gigabuddy-knowledge-status" in gigabuddy
    ks_start = gigabuddy.index("function renderKnowledgeStatus")
    ks_end = gigabuddy.index("\n}", ks_start)
    ks = gigabuddy[ks_start:ks_end]
    # Reads the live camelCase view fields (status + counts + llmBuilt).
    assert "status" in ks and "docCount" in ks and "chunkCount" in ks
    # Honest states: building/ready/empty/error are all represented.
    for label in ("building", "ready", "empty", "error"):
        assert label in ks or label in gigabuddy
    # Content is escaped; renderer emits classes/markup, not inline styles.
    assert ".style." not in ks

    # --- normalizeKnowledgeBase clamps status + floors the counts defensively.
    nk_start = gigabuddy.index("function normalizeKnowledgeBase")
    nk_end = gigabuddy.index("\n}", nk_start)
    nk = gigabuddy[nk_start:nk_end]
    assert "docCount" in nk and "chunkCount" in nk and "llmBuilt" in nk

    # --- CSS: the indicator + pulsing "building" dot use the accent variable,
    # follow glassmorphism, and add no inline styles.
    assert ".gigabuddy-knowledge-status {" in css
    assert '.gigabuddy-knowledge-status[data-status="building"]' in css
    assert '.gigabuddy-knowledge-status[data-status="ready"]' in css
    assert "gigabuddy-knowledge-pulse" in css
    assert "var(--gigabuddy-accent" in css

    # --- backend: the view is enriched view-pure via knowledge_status (no LLM on
    # the status path); the gateway fires the rebuild out-of-band (non-blocking).
    assert "def _knowledge_base_view" in gb_state
    assert "knowledgeBase" in gb_state
    assert "def knowledge_status" in gk
    assert 'return {"status": "empty"' in gk or "\"status\": \"empty\"" in gk
    # v6.87.3: simplified keyword retrieval — no LLM builder, no .wiki_index/
    # persistence; the index builds on demand + memory cache.
    assert "def rebuild_knowledge" in gk
    assert "_WIKI_INDEX_DIRNAME" not in gk
    assert "_llm_build_chunks" not in gk
    # The gateway rebuild trigger is kept as a no-op seam (no background daemon).
    assert "_maybe_trigger_knowledge_rebuild" in settings
    # No frozen contract churn for the knowledge-base status data.
    assert "knowledgebase" not in contracts.lower()
    assert "gigabuddy" not in contracts.lower()


def test_server_navigation_and_chat_static_contracts():
    server_source = _read("server.py")
    state_source = _read("ouroboros/gateway/state.py")
    control_source = _read("ouroboros/gateway/control.py")
    app_source = _read("web/app.js")
    evo_source = _read("web/modules/evolution.js")
    chat_source = _read("web/modules/chat.js")
    css = _read("web/style.css")
    ui = _read("web/modules/settings_ui.js")
    settings = _read("web/modules/settings.js")
    costs = _read("web/modules/costs.js")

    assert "def _describe_bg_consciousness_state(requested_enabled: bool) -> dict:" in server_source
    assert '"evolution_state": evolution_state,' in state_source
    assert '"bg_consciousness_state": bg_state,' in state_source
    assert 'request.query_params.get("force")' in control_source
    assert "window.dispatchEvent(new CustomEvent('ouro:page-shown', { detail: { page: pageName } }));" in app_source
    assert "evo-runtime-detail" in evo_source
    assert "data?.evolution_state?.detail" in chat_source
    assert "data?.bg_consciousness_state?.detail" in chat_source
    assert re.search(r'<input[^>]+id="chat-file-input"[^>]+multiple', chat_source)
    assert "MAX_PENDING_ATTACHMENTS = 10" in chat_source
    assert "MAX_ATTACHMENT_FILE_BYTES = 50 * 1024 * 1024" in chat_source
    assert "MAX_PENDING_ATTACHMENT_BYTES = 100 * 1024 * 1024" in chat_source
    assert "pendingAttachments" in chat_source
    assert "attachmentsUploading" in chat_source
    assert "setAttachmentUploadState" in chat_source
    assert "attachBtn.classList.toggle('uploading', uploading)" in chat_source
    assert "input.disabled = uploading;" in chat_source
    assert "cleanupUploadedAttachments" in chat_source
    assert "method: 'DELETE'" in chat_source
    assert "await cleanupUploadedAttachments(uploaded);" in chat_source
    assert "await cleanupUploadedAttachments(uploadedAttachments);" in chat_source
    assert "ws.send({" in chat_source and "{ queue: false }" in chat_source
    assert "result?.status !== 'sent'" in chat_source
    assert "data-attachment-remove" in chat_source
    assert "Promise.allSettled" in chat_source
    assert '>Loading…</span>' in chat_source
    assert "syncHeaderControlState({ accounting: { available: false } });" in chat_source
    assert "budget_text: 'Connecting...'" not in chat_source
    assert "send(msg, options = {})" in _read("web/modules/ws.js")
    assert "options.queue === false" in _read("web/modules/ws.js")
    assert ".chat-attachment-preview" in css and "flex-wrap" in css
    assert 'id="s-total-budget"' in ui
    assert 'id="s-settings-per-task-cost"' in ui
    assert "setupContract.budgetFields" in settings
    assert "'anthropic/claude-opus-4.7'" in settings
    assert "'anthropic::claude-opus-4-7'" in settings
    assert "currentSettings?.[field.settingKey]" in settings
    assert "window.addEventListener('ouro:settings-updated'" in settings
    assert "source: 'settings'" in settings
    assert "Budget values must be at least 0.01." in costs
    assert "COST_BUDGET_INPUTS" in costs
    assert "s?._meta?.setup_contract?.budgetFields" in costs
    assert "const MIN_BUDGET_VALUE" not in costs
    assert "new CustomEvent('ouro:settings-updated'" in costs
    assert "source: 'costs'" in costs
    assert "event.detail?.source === 'costs'" in costs
